### PR TITLE
Lesson 1.7

### PR DESCRIPTION
**Pull request by Mbareck21**

### CODE REVIEW

**Comment by royemosby** [comment]
@Mbareck21 I think you unintentionally made a PR against CTD's repo. Please open a PR against your own repo for your assignment submission. Hit me up on Slack if you have any questions.

**Comment by Mbareck21** [comment]
Hi Roy,
That us true. I realized that and fixed it, but did not cancel the request
the CTD. In other words, I have another pull request directly from my repo.
Should I remove this one from CTD?

Thank you for the notification

**Comment by royemosby** [comment]
@Mbareck21 If you can do so. I'm unsure of how the permissions are set up on this repo. It's not a huge deal as I've done the same several times myself. I just want to make sure your work ends up in a place that will not get lost.

**Comment by Mbareck21** [comment]
Done with thanks

**Pull request closed without merging**
